export const LOAD_PERSONS = "LOAD_PERSONS";
export const GET_ERROR_WHEN_UPLOAD_CHARACTER_LIST =
  "GET_ERROR_WHEN_UPLOAD_CHARACTER_LIST";
export const CHANGE_STATUS_LOADER = "CHANGE_STATUS_LOADER";
export const LOAD_CURRENT_PERSON = "LOAD_CURRENT_PERSON";
export const CHANGE_STATUS_LOADER_CURRENT_PERSON =
  "CHANGE_STATUS_LOADER_CURRENT_PERSON";
export const GET_ERROR_WHEN_UPLOAD_CURRENT_PERSON =
  "GET_ERROR_WHEN_UPLOAD_CURRENT_PERSON";
export const CLEAN_CURRENT_PERSON = "CLEAN_CURRENT_PERSON";
export const GET_QUOTE = "GET_QUOTE";
